Repository RayanBassetti/quiz-pm-front, pull requests merged in 2020-11, with the labels that each got.

#3 Feature : Routing, connection between the pages with the user info
  debug.log
  package-lock.json
  package.json
  public/index.html
  src/components/App.js
  src/components/common/QuizButton.js
  src/components/contexts/UsersContext.js
  src/components/ending/Ending.js
  src/components/home/Home.js
  src/components/home/HomeRight.js
  src/components/leaderboard/Leaderboard.js
  src/components/quiz/Quiz.js
  src/components/quiz/QuizContent.js
  src/components/quiz/QuizProgression.js
  src/components/routes/RoutingSwitch.js
Labels: enhancement

#5 Feature : Context pour le quiz
  src/components/App.js
  src/components/common/QuizButton.js
  src/components/contexts/QuizContext.js
  src/components/quiz/Quiz.js
  src/components/quiz/QuizContent.js
Labels: enhancement

#7 update : ajout de la gestion des questions/réponses
  debug.log
  src/components/contexts/QuizContext.js
  src/components/quiz/QuizContent.js
Labels: enhancement

#8 update : ajout du fil d'ariane pour suivre la progression lors du quiz
  src/components/quiz/Quiz.js
  src/components/quiz/QuizProgression.js
Labels: enhancement

#9 css answers details
  src/components/ending/AnswersDetails.js
  src/components/ending/Ending.js
  src/css/index.css
Labels: enhancement

#10 update :
  src/components/common/QuizButton.js
  src/components/ending/AnswersDetails.js
  src/components/ending/Ending.js
  src/components/home/Home.js
  src/components/home/HomeLeft.js
  src/components/home/HomeRight.js
  src/components/quiz/Quiz.js
  src/components/quiz/QuizContent.js
  src/components/quiz/QuizProgression.js
Labels: enhancement

#11 update :
  src/components/contexts/QuizContext.js
  src/components/quiz/Quiz.js
Labels: enhancement

#12 update :
  src/components/common/QuizButton.js
  src/components/contexts/QuizContext.js
  src/components/quiz/Quiz.js
Labels: enhancement

#13 mobile + fix
  src/components/ending/AnswersDetails.js
  src/css/index.css
Labels: enhancement

#15 update :
  package-lock.json
  src/components/common/QuizButton.js
  src/components/contexts/UsersContext.js
  src/components/ending/Ending.js
  src/components/leaderboard/Leaderboard.js
  src/components/leaderboard/LeaderboardTable.js
Labels: enhancement

#16 fix : fix du routing sur le déploiement
  public/_redirects
Labels: fix

#17 update : ajout des autres APIS + tentative fix post request à la fin
  src/components/common/Methods.js
  src/components/contexts/QuizContext.js
  src/components/contexts/UsersContext.js
  src/components/quiz/Quiz.js
Labels: enhancement, fix

#18 Feature routes
  src/components/common/Methods.js
  src/components/contexts/QuizContext.js
  src/components/contexts/UsersContext.js
  src/components/leaderboard/Leaderboard.js
  src/components/leaderboard/LeaderboardTable.js
Labels: enhancement, fix

#19 update : du code pas dingue pour rendre le truc plus sympa à faire
  src/components/common/Background.js
  src/components/ending/Ending.js
  src/components/ending/EndingText.js
  src/components/home/HomeLeft.js
  src/components/imgs/batman.jpg
  src/components/imgs/curie.png
  src/components/imgs/diane.jpg
  src/components/imgs/kratos.jpg
  src/components/imgs/matrix.jpg
  src/components/imgs/mims.png
  src/components/imgs/veil.jpg
  src/components/leaderboard/Leaderboard.js
  src/css/index.css
Labels: enhancement

#21 Feature bonusetleaderboard
  src/components/contexts/QuizContext.js
  src/components/ending/EndingText.js
  src/components/home/HomeRight.js
  src/components/leaderboard/Leaderboard.js
  src/components/leaderboard/LeaderboardTable.js
  src/components/quiz/Quiz.js
  src/components/quiz/QuizProgression.js
Labels: enhancement, fix

#22 end update
  .gitignore
  README.md
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  src/App.js
  src/components/App.js
  src/components/common/Background.js
  src/components/common/Methods.js
  src/components/common/QuizButton.js
  src/components/contexts/QuizContext.js
  src/components/contexts/UsersContext.js
  src/components/ending/AnswersDetails.js
  src/components/ending/Ending.js
  src/components/ending/EndingText.js
  src/components/home/Home.js
  src/components/home/HomeLeft.js
  src/components/home/HomeRight.js
  src/components/imgs/batman.jpg
  src/components/imgs/curie.png
  src/components/imgs/diane.jpg
  src/components/imgs/kratos.jpg
  src/components/imgs/matrix.jpg
  src/components/imgs/mims.png
  src/components/imgs/veil.jpg
  src/components/leaderboard/Leaderboard.js
  src/components/leaderboard/LeaderboardTable.js
  src/components/quiz/Quiz.js
  src/components/quiz/QuizContent.js
  src/components/quiz/QuizProgression.js
  src/components/routes/RoutingSwitch.js
  src/css/App.css
  src/css/index.css
  src/index.css
  src/index.js
  src/logo.svg
Labels: enhancement
